---
title: "딥러닝"
subtitle: "R 딥러닝 환경설정: `openmp` 맥"
author:
  - name: "[Tidyverse Korea](https://www.facebook.com/groups/tidyverse/)"
    url: https://www.facebook.com/groups/tidyverse/
    affiliation: Tidyverse Korea
    affiliation_url: https://www.facebook.com/groups/tidyverse/
date: "`r Sys.Date()`"
output:
  html_document: 
    theme: journal
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
bibliography: bibliography.bib
csl: biomed-central.csl
urlcolor: blue
linkcolor: blue
editor_options: 
  chunk_output_type: console
---

``` {r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')
```


> clang: warning: argument unused during compilation: '-fopenmp' <br>
> fatal error: 'omp.h' file not found

# 딥러닝 팩키지 설치 {#install-deep-learning}

딥러닝 팩키지를 설치할 때 `C`에 대한 의존성 문제를 정확히 이해하고 해결해야 이후 발생되는 문제를 원만하게 해결할 수 있다.
[OpenMP](https://www.openmp.org/)는 공용 메모리(shared memory)기반 CPU 멀티코어를 이용하여 병렬처리(parallel processing)를 지원하는 패러다임이다. 맥 최신 OS에서 OpenMP 관련 컴파일러가 변경되어 기존 방식으로 처리할 경우 R에서 문제가 발생된다.

- [R COMPILER TOOLS FOR RCPP ON MACOS](https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos/)
- [Installer Package for macOS R toolchain](https://github.com/rmacoslib/r-macos-rtools)
- [[R-SIG-Mac] clang: error: unsupported option '-fopenmp'](https://stat.ethz.ch/pipermail/r-sig-mac/2019-May/012985.html)

[`image.libfacedetection`](https://github.com/bnosac/image) 팩키지를 통해 얼굴인식을 할 경우 맥에 C 컴파일러가 필요한데 애플에서 지원하는 C 컴파일러와 호환 문제가 제기된다. 이를 해결하기 위한 다양한 방법인데, `R for Mac OS X`에서 관리하는 
[R for Mac OS X: Development Tools and Libraries](https://cran.r-project.org/bin/macosx/tools/) 웹사이트에 윈도우 Rtools 4.X와 마찬가지로 맥 개발도구와 라이브러리를 설치한 후 환경 설정을 하는 것이 나름 깔끔한 해결방법이 아닌가 쉽다.


# 해결방안 [^coatless-blog] {#solution-openmp}

[^coatless-blog]: ["OPENMP IN R ON OS X", March 19, 2016, THE COATLESS PROFESSOR](https://thecoatlessprofessor.com/programming/cpp/openmp-in-r-on-os-x/)

1. [R for Mac OS X: Development Tools and Libraries](https://cran.r-project.org/bin/macosx/tools/) 웹사이트에서 `clang-7.0.0.pkg` 혹은 `clang-8.0.0.pkg` 팩키지를 다운로드 받아 설치한다.
1. `~/.Renviron` 파일에 다음 내용을 추가한다.
    - `PATH="/usr/local/clang7/bin:${PATH}"`
1. 혹은 `~/.Renviron` 파일 대신에 ```~/.R/Makevars` 파일에 ``CXX`, `CXX11` , ...` 설정을 해두곤 했으나 오래된 방법으로 필요한 경우 참고하여 사용한다.



