---
title: "딥러닝"
subtitle: "`YOLO`: 캡챠 깨기"
author:
  - name: "[Tidyverse Korea](https://www.facebook.com/groups/tidyverse/)"
    url: https://www.facebook.com/groups/tidyverse/
    affiliation: Tidyverse Korea
    affiliation_url: https://www.facebook.com/groups/tidyverse/
date: "`r Sys.Date()`"
output:
  html_document: 
    theme: journal
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
bibliography: bibliography.bib
csl: biomed-central.csl
urlcolor: blue
linkcolor: blue
editor_options: 
  chunk_output_type: console
---

``` {r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

knitr::opts_knit$set(global.par = TRUE) 
```

# `YOLO`


```{r yolo-install, eval = FALSE}
devtools::install_github("bnosac/image",
                         subdir = "image.darknet",
                         build_vignettes = TRUE)

```

```{r yolo-library, eval = FALSE}
library(image.darknet)


# Define the detection model (YOLO)  ------------------------------------------
## https://pjreddie.com/darknet/yolo/
## (structure of the deep learning model + the learned weights + the labels)

labels_VOC <- readLines(
  system.file(package="image.darknet", "include", "darknet", "data", 
              "voc.names")
)

labels_COCO <- readLines(
  system.file(package="image.darknet", "include", "darknet", "data", 
              "coco.names")
)

cfg <- "model_detection/yolov2-tiny-voc.cfg"
weights <- "model_detection/yolov2.weights"

yolo_COCO <- image_darknet_model(type = 'detect', 
                                 model = cfg, 
                                 weights = weights, 
                                 labels = labels_COCO)

yolo_COCO$labels


image_darknet_detect(file = f, 
                     object = yolo_COCO)

```

