---
title: "딥러닝"
subtitle: "사람 얼굴 인식"
author:
  - name: "[Tidyverse Korea](https://www.facebook.com/groups/tidyverse/)"
    url: https://www.facebook.com/groups/tidyverse/
    affiliation: Tidyverse Korea
    affiliation_url: https://www.facebook.com/groups/tidyverse/
date: "`r Sys.Date()`"
output:
  html_document: 
    theme: journal
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
bibliography: bibliography.bib
csl: biomed-central.csl
urlcolor: blue
linkcolor: blue
editor_options: 
  chunk_output_type: console
---

``` {r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

knitr::opts_knit$set(global.par = TRUE) 
```

# 사람 얼굴인식 [^bnosac-image] {#recognize-face}

[^bnosac-image]: [image - Computer Vision and Image Recognition algorithms for R users](https://github.com/bnosac/image)

[`bnosac`](https://github.com/bnosac/image) GitHub 저장소에서 이미지 딥러닝 처리에 필요한 팩키지를 설치한다. 맥OS에서 설치할 때 발생되는 문제점 `OpenMP`문제는 [R 딥러닝 환경설정: `openmp` 맥](http://statkclee.github.io/deep-learning/dl-mac-openmp.html)를 참조한다.

```{r face-recognition, eval = FALSE}
devtools::install_github("bnosac/image",
                         subdir = "image.dlib",
                         build_vignettes = TRUE)

devtools::install_github("bnosac/image",
                         subdir = "image.libfacedetection",
                         build_vignettes = TRUE)
```

## 사진 이미지 살펴보기 {#recognize-face-picture}

`magick` 팩키지로 사진을 일별한다. 

```{r face-recognition-package}
library(tidyverse)
library(magick)
library(image.libfacedetection)

test_image <- magick::image_read("fig/people.jpg")

test_image <- test_image %>% 
  image_resize("700")

test_image
```

## 얼굴 추출 {#recognize-face-extraction}

`image_detect_faces()` 함수로 사진속 얼굴을 식별한다.

```{r face-recognition-detect}
test_face <- image_detect_faces(test_image)

print(test_face)
```

## 추출결과 확인 {#recognize-face-confirm}

원본 사진과 인식된 얼굴을 겹쳐 추출결과를 시각적으로 확인한다.

```{r face-picture-overlay}

plot(test_face, test_image,
    border = "red",
    lwd = 5,
    col = "blue")
```


