---
layout: page
title: xwMOOC 딥러닝
subtitle: "이미지 주석/라벨(annotation) 달기"
author:
  - name: Tidyverse Korea
    url: https://www.facebook.com/groups/tidyverse/
    affiliation: Tidyverse Korea
    affiliation_url: https://www.facebook.com/groups/tidyverse/
date: "`r Sys.Date()`"
output:
  html_document: 
    theme: journal
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
bibliography: bibliography.bib
csl: biomed-central.csl
urlcolor: blue
linkcolor: blue
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

```

# 캡챠 데이터셋 [^nanonets] [^captcha-tutorail] {#captcha-dataset}

[^nanonets]: [Rahul Agarwal (2019), "Deep Learning Based OCR for Text in the Wild", Nanonets](https://nanonets.com/blog/deep-learning-ocr/)

[^captcha-tutorail]: ["Captcha Breaking Tutorial"](https://cagriuysal.github.io/Simple-Captcha-Breaker/)

## 헬로월드 {#captcha-hello-world}

먼저 이미지 데이터와 라벨 데이터를 다운로드 받는다.

```{r captcha-dataset}
library(tidyverse)
library(magick)

one_img <- image_read("data/captcha_tutorial/9.jpeg")

one_img
```

## 이미지 + 라벨 {#merge-image-label}

캡챠 이미지 데이터와 라벨데이터를 결합 시켜보자.

```{r captcha-merge-label}
library(glue)

filename <- list.files("data/captcha_tutorial/", pattern = "*.jpeg")

file_names_seq <- basename(filename) %>% 
  str_remove(pattern = ".jpeg") %>% 
  as.integer()

train_labels <- read_csv("data/captcha_tutorial/labels.txt", col_names = FALSE) %>% 
  rename(label = X1)

captcha_df <- tibble(filename = filename,
  filename_seq = file_names_seq) %>% 
  arrange(file_names_seq) %>% 
  slice(1:5000) %>% 
  bind_cols(train_labels) %>% 
  mutate(image = glue("data/captcha_tutorial/{filename_seq}.jpeg"))

captcha_df %>% tail
```

## 캡챠 갤러리 {#captcha-gallery}

```{r captcha-gallery}
library(trelliscopejs)

captcha_sample <- captcha_df %>%
  sample_n(100) %>%
  mutate(label = as.character(label),
         image = as.character(image),
         panel = img_panel_local(image))

trelliscope(captcha_sample, name = "captcha_tutorial", 
            nrow = 3, ncol = 7,
            path="captcha_tutorial"
            )
```

