---
layout: page
title: xwMOOC 딥러닝
subtitle: "필기숫자 인식 데이터(MNIST): 파이썬 스크립트"
author:
  - name: Tidyverse Korea
    url: https://www.facebook.com/groups/tidyverse/
    affiliation: Tidyverse Korea
    affiliation_url: https://www.facebook.com/groups/tidyverse/
date: "`r Sys.Date()`"
output:
  html_document: 
    theme: journal
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
bibliography: bibliography.bib
csl: biomed-central.csl
urlcolor: blue
linkcolor: blue
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

```

# MNIST 데이터셋 [^mnist-keras] {#mnist-python-dataset}

[^mnist-keras]: [Keras Documentation: Trains a simple convnet on the MNIST dataset.](https://keras.io/examples/mnist_cnn/)

Keras 내장된 mnist 데이터셋을 파이썬 코드로 인식하게 작성한다.

```{r keras-mnist}
library(reticulate)

# py_run_file("code/mnist-keras.py")
```

```{r keras-mnist-function, eval=FALSE}
source_python("code/mnist-keras-function.py")
mnist_function()
```

# 손글씨 인식기 {#mnist-python-classifier}

함수로 작성하여 결과를 R로 반환시켜 추가 작업을 수행한다.

```{r keras-mnist-function-object, eval = FALSE}
source_python("code/mnist-keras-function-object.py")
score <- mnist_function()

cat('Test loss:', score[1])
cat('Test accuracy:', score[2])
```

# 예측값 {#mnist-python-classifier-predict}

함수로 작성하여 결과를 R로 반환시켜 추가 작업을 수행한다.

```{r keras-mnist-function-object-predict}
library(tidyverse)

source_python("code/mnist-keras-function-object-predict.py")
result <- mnist_function()

tibble(y_pred = result[[0]], y_label = result[[1]])

y_pred <- result[[1]]
y_label <- result[[2]]

y_pred %>% as_tibble()
y_label %>% as_tibble()

```
