---
title: "딥러닝"
subtitle: "`xaringan` 발표자료 유튜브 동영상 자동 제작"
author:
  - name: "[Tidyverse Korea](https://www.facebook.com/groups/tidyverse/)"
    url: https://www.facebook.com/groups/tidyverse/
    affiliation: Tidyverse Korea
    affiliation_url: https://www.facebook.com/groups/tidyverse/
date: "`r Sys.Date()`"
output:
  html_document: 
    include:
      after_body: footer.html
      before_body: header.html
    theme: journal
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
bibliography: bibliography.bib
csl: biomed-central.csl
urlcolor: blue
linkcolor: blue
editor_options: 
  chunk_output_type: console
---

``` {r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

knitr::opts_knit$set(global.par = TRUE) 
```

# 파워포인트 원본파일 {#original-pptx}

파워포인트 동영상 제작에 사용된 원본 파일은 [다운로드](data/Xaringan_OCR.pptx) 받아 직접 실습에 사용할 수 있다.
[`pptx` &rarr; `png`](https://statkclee.github.io/deep-learning/r-ari.html#3_PPT_%E2%86%92_%EB%B0%9C%ED%91%9C%EB%8F%99%EC%98%81%EC%83%811) 변환결과를 웹사이트에서 확인할 수 있다.
이제 PPT 파일을 `xaringan` 파일로 변환해보자.

# `xaringan` 발표자료 [^how-to-presentor-notes] [^RaukR-xaringan-demo] {#xaringan-slideshow}

[^how-to-presentor-notes]: [Claus Thorn Ekstrøm (September 26th, 2019), "Xaringan shenanigans", Copenhagen R users](https://www.biostatistics.dk/talks/CopenhagenRuseRs-2019/index.html)

[^RaukR-xaringan-demo]: [Roy Francis, "RaukR presentation demo", RaukR 2019 • Advanced R for Bioinformatics](https://github.com/NBISweden/raukrtemplate)


`???` 뒤에 작성되는 발표자 노트는 `P` 키를 눌렀을 때 나타나게 된다. 이제 PPT 슬라이드를 `xaringan`에 맞춰 하나하나 차근히 변환시켜보자.

```{r embed-xaringan-ocr}
knitr::include_url('xaringan-OCR.html')
```


# 

