---
title: "딥러닝"
subtitle: "한국 R 컨퍼런스 - Julia Silge Keynote번역"
author:
  - name: "[Tidyverse Korea](https://www.facebook.com/groups/tidyverse/)"
    url: https://www.facebook.com/groups/tidyverse/
    affiliation: Tidyverse Korea
    affiliation_url: https://www.facebook.com/groups/tidyverse/
date: "`r Sys.Date()`"
output:
  html_document: 
    include:
      after_body: footer.html
      before_body: header.html
    theme: journal
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
bibliography: bibliography.bib
csl: biomed-central.csl
urlcolor: blue
linkcolor: blue
editor_options: 
  chunk_output_type: console
---

``` {r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

knitr::opts_knit$set(global.par = TRUE) 
```


```{r julia-silge}
library(embedr)

embed_audio("data/15_silge.mp3")


```


Cloud Speech-to-Text API

```{r tts-hello, error=TRUE}
library(googleLanguageR)

kt_config <- list(encoding = "FLAC",
                  audioChannelCount = 2,
                  diarizationConfig = list(
                    enableSpeakerDiarization = TRUE
                  ))

test_gcs <- "gs://mark-edmondson-public-files/googleLanguageR/a-dream-mono.wav"


julia_tts <-  gl_speech("https://storage.googleapis.com/rconf-keynote/15_silge.flac", languageCode = "en-US", customConfig = kt_config)

```


